<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CarSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('cars')->insert([
            [
                'category_id'    => 1,
                'mark'           => 'Toyota',
                'type'           => 'SUV',
                'model'          => 'RAV4',
                'color'          => 'Noir',
                'photo'          => 'images/cars/toyota_rav4.png',
                'imatriculation' => 'TG-1234-AB',
                'description'    => 'SUV compact et confortable',
                'status'         => 'disponible',
                'kmAmount'       => 5.50,
                'dayAmount'      => 50.00,
                'state'          => 'Neuf',
                'place'          => 5,
                'door'           => 4,
                'kilometrage'    => 20000,
                'niveauCarburant'=> 80,
                'domage'         => null,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'category_id'    => 2,
                'mark'           => 'Hyundai',
                'type'           => 'Berline',
                'model'          => 'Elantra',
                'color'          => 'Blanc',
                'photo'          => 'images/cars/hyundai_elantra.png',
                'imatriculation' => 'TG-5678-CD',
                'description'    => 'Berline économique et fiable',
                'status'         => 'loué',
                'kmAmount'       => 4.75,
                'dayAmount'      => 40.00,
                'state'          => 'Bon état',
                'place'          => 5,
                'door'           => 4,
                'kilometrage'    => 35000,
                'niveauCarburant'=> 60,
                'domage'         => 'Rayure légère',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'category_id'    => 3,
                'mark'           => 'BMW',
                'type'           => 'Sportive',
                'model'          => 'M3',
                'color'          => 'Rouge',
                'photo'          => 'images/cars/bmw_m3.png',
                'imatriculation' => 'TG-9012-EF',
                'description'    => 'Voiture sportive haut de gamme',
                'status'         => 'disponible',
                'kmAmount'       => 8.00,
                'dayAmount'      => 120.00,
                'state'          => 'Neuf',
                'place'          => 4,
                'door'           => 2,
                'kilometrage'    => 15000,
                'niveauCarburant'=> 90,
                'domage'         => null,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'category_id'    => 4,
                'mark'           => 'Mercedes',
                'type'           => 'Pickup',
                'model'          => 'X-Class',
                'color'          => 'Gris',
                'photo'          => 'images/cars/mercedes_xclass.png',
                'imatriculation' => 'TG-3456-GH',
                'description'    => 'Pickup robuste et élégant',
                'status'         => 'en maintenance',
                'kmAmount'       => 6.25,
                'dayAmount'      => 70.00,
                'state'          => 'Bon état',
                'place'          => 5,
                'door'           => 4,
                'kilometrage'    => 50000,
                'niveauCarburant'=> 50,
                'domage'         => 'Choc arrière',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'category_id'    => 5,
                'mark'           => 'Peugeot',
                'type'           => 'Citadine',
                'model'          => '208',
                'color'          => 'Bleu',
                'photo'          => 'images/cars/peugeot_208.png',
                'imatriculation' => 'TG-7890-IJ',
                'description'    => 'Petite citadine pratique',
                'status'         => 'indisponible',
                'kmAmount'       => 3.50,
                'dayAmount'      => 30.00,
                'state'          => 'Usé',
                'place'          => 5,
                'door'           => 4,
                'kilometrage'    => 80000,
                'niveauCarburant'=> 20,
                'domage'         => 'Pare-chocs abîmé',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
        ]);
    }
}
